// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ScanOptions {
    "scanners": string[] | null;
    "severity": string[] | null;
    "ignoreUnfixed": boolean;
    "skipDbUpdate": boolean;
    "extraArgs": string[] | null;
}
