// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rule$0 from "../rule/models.js";

export interface Finding {
    "id": string;
    "scanId"?: string;
    "ruleId": string;
    "ruleTitle": string;
    "severity": rule$0.Severity;
    "resourceKind": string;
    "resourceName": string;
    "namespace": string | null;
    "message": string;
}

export interface Scan {
    "id": string;
    "projectId": string;
    "status": ScanStatus;
    "context": string | null;
    "error": string | null;
    "findingCount": number;
    "startedAt": string;
    "finishedAt": string;
}

export interface ScanResult {
    "scan": Scan;
    "findings": Finding[] | null;
}

export enum ScanStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusCompleted = "completed",
    StatusFailed = "failed",
};
