// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetScan(id: string): $CancellablePromise<$models.Scan | null> {
    return $Call.ByID(3477173815, id);
}

export function ListScanFindings(scanID: string): $CancellablePromise<$models.Finding[] | null> {
    return $Call.ByID(1643389645, scanID);
}

export function ListScans(projectID: string): $CancellablePromise<$models.Scan[] | null> {
    return $Call.ByID(2122534940, projectID);
}

export function PreviewScan(): $CancellablePromise<$models.Finding[] | null> {
    return $Call.ByID(3653413471);
}

export function RunScan(projectID: string): $CancellablePromise<$models.ScanResult> {
    return $Call.ByID(2459380534, projectID);
}
