// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum ImportMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImportMerge = "merge",
    ImportReplace = "replace",
};

export interface ImportSummary {
    "created": number;
    "updated": number;
    "skipped": SkippedRule[] | null;
}

export enum Operator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OpEquals = "equals",
    OpNotEquals = "notEquals",
    OpPresent = "present",
    OpAbsent = "absent",
    OpArrayExcludes = "arrayExcludes",
};

export interface Rule {
    "id": string;
    "ruleId": string;
    "title": string;
    "description": string;
    "severity": Severity;
    "resourceType": string;
    "fieldPath": string;
    "operator": Operator;
    "expectedValue": string;
    "importId": string | null;
    "createdAt": string;
    "updatedAt": string;
}

export interface RuleInput {
    "title": string;
    "description": string;
    "severity": Severity;
    "resourceType": string;
    "fieldPath": string;
    "operator": Operator;
    "expectedValue": string;
}

export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityCritical = "critical",
    SeverityHigh = "high",
    SeverityMedium = "medium",
    SeverityLow = "low",
};

export interface SkippedRule {
    "id": string;
    "title": string;
    "reason": string;
}
