// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ClusterStatus {
    "connected": boolean;
    "healthy": boolean;
    "context": string | null;
    "error": string | null;
}

export interface KubeContexts {
    "current": string | null;
    "contexts": string[] | null;
}
