// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateRule(input: $models.RuleInput): $CancellablePromise<$models.Rule> {
    return $Call.ByID(864752825, input);
}

export function DeleteRule(id: string): $CancellablePromise<void> {
    return $Call.ByID(1485501250, id);
}

export function ExportRules(path: string): $CancellablePromise<number> {
    return $Call.ByID(1712418024, path);
}

export function GetRule(id: string): $CancellablePromise<$models.Rule | null> {
    return $Call.ByID(2250464767, id);
}

export function ImportRules(path: string, mode: $models.ImportMode): $CancellablePromise<$models.ImportSummary> {
    return $Call.ByID(1055735217, path, mode);
}

export function ListRules(): $CancellablePromise<$models.Rule[] | null> {
    return $Call.ByID(514224862);
}

export function UpdateRule(id: string, input: $models.RuleInput): $CancellablePromise<$models.Rule> {
    return $Call.ByID(1289745112, id, input);
}
