// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ConnectCluster(kubeContext: string | null): $CancellablePromise<$models.ClusterStatus> {
    return $Call.ByID(1595945690, kubeContext);
}

export function DisconnectCluster(): $CancellablePromise<$models.ClusterStatus> {
    return $Call.ByID(1081736278);
}

export function ListKubeContexts(): $CancellablePromise<$models.KubeContexts> {
    return $Call.ByID(3464942275);
}

export function ProbeCluster(): $CancellablePromise<$models.ClusterStatus> {
    return $Call.ByID(1771379294);
}
