// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LocalImage {
    "id": string;
    "reference": string;
    "repository": string;
    "tag": string;
    "size": string;
    "sizeBytes": number | null;
}

export interface LocalImageList {
    "runtime": string;
    "images": LocalImage[] | null;
}
