// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Project {
    "id": string;
    "name": string;
    "kind": ProjectKind;
    "config": ProjectConfig;
    "createdAt": string;
    "updatedAt": string;
}

export interface ProjectConfig {
    "context": string | null;
    "image"?: string | null;
    "images": string[] | null;
}

export interface ProjectInput {
    "name": string;
    "kind": ProjectKind;
    "config": ProjectConfig;
}

export enum ProjectKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindKubernetesClusterReview = "kubernetesClusterReview",
    KindContainerImageReview = "containerImageReview",
};
