// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateProject(input: $models.ProjectInput): $CancellablePromise<$models.Project> {
    return $Call.ByID(2688893764, input);
}

export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(4016229121, id);
}

export function GetProject(id: string): $CancellablePromise<$models.Project | null> {
    return $Call.ByID(282818338, id);
}

export function ListProjects(): $CancellablePromise<$models.Project[] | null> {
    return $Call.ByID(4285493493);
}

export function UpdateProject(id: string, input: $models.ProjectInput): $CancellablePromise<$models.Project> {
    return $Call.ByID(2320046399, id, input);
}
